language: node_js
node_js:
- '10.16'
before_install:
- openssl aes-256-cbc -K $encrypted_cc020c128726_key -iv $encrypted_cc020c128726_iv
  -in deploy.key.enc -out deploy.key -d

- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy.key
- ssh-add .travis/deploy.key
- ssh-keyscan gibson.markrailton.com >> ~/.ssh/known_hosts
- git remote add production dokku@gibson.markrailton.com:wwcd-api
- git remote add staging dokku@gibson.markrailton.com:wwcd-staging-api
- git config --global push.default simple

deploy:
  - provider: script
    script: git push production master
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: git push staging staging:master
    skip_cleanup: true
    on:
      branch: staging
