"""create searches table

Revision ID: 29e0350c8604
Revises: 2826cbb9237a
Create Date: 2020-05-11 15:05:26.151170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29e0350c8604'
down_revision = '2826cbb9237a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('oic', sa.String(length=255), nullable=True),
    sa.Column('sm', sa.String(length=255), nullable=True),
    sa.Column('so', sa.String(length=255), nullable=True),
    sa.Column('sl', sa.String(length=255), nullable=True),
    sa.Column('ro', sa.String(length=255), nullable=True),
    sa.Column('scribe', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('searches')
    # ### end Alembic commands ###
