"""create searches_radioassignments table

Revision ID: 8ccfcb49dbdd
Revises: d6d561348a58
Create Date: 2020-05-14 12:56:10.674759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ccfcb49dbdd'
down_revision = 'd6d561348a58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_radioassignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=True),
    sa.Column('call_sign', sa.String(length=10), nullable=True),
    sa.Column('tetra_number', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_radioassignments')
    # ### end Alembic commands ###
