"""Adds area to search_search_log

Revision ID: 934b74ac20ce
Revises: cc304e841bed
Create Date: 2020-05-15 17:32:44.327579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934b74ac20ce'
down_revision = 'cc304e841bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_searchlog', sa.Column('area', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_searchlog', 'area')
    # ### end Alembic commands ###
