"""Adds technical_team table

Revision ID: a3d4c274228d
Revises: af9d0741c4cc
Create Date: 2020-06-08 13:15:40.751025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3d4c274228d'
down_revision = 'af9d0741c4cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_technical_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('search_id', sa.Integer(), nullable=True),
    sa.Column('equipment_type', sa.String(length=255), nullable=False),
    sa.Column('member_1', sa.String(length=255), nullable=False),
    sa.Column('member_2', sa.String(length=255), nullable=True),
    sa.Column('member_3', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_technical_teams')
    # ### end Alembic commands ###
