"""adds timestamps to search teams

Revision ID: cc304e841bed
Revises: f2794bfbb152
Create Date: 2020-05-14 18:34:29.295760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc304e841bed'
down_revision = 'f2794bfbb152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_teams', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('search_teams', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_teams', 'updated_at')
    op.drop_column('search_teams', 'created_at')
    # ### end Alembic commands ###
