"""creates search_teams table

Revision ID: d6d561348a58
Revises: 29e0350c8604
Create Date: 2020-05-11 19:27:21.605125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6d561348a58'
down_revision = '29e0350c8604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=True),
    sa.Column('team_leader', sa.String(length=255), nullable=False),
    sa.Column('medic', sa.String(length=255), nullable=False),
    sa.Column('responder_1', sa.String(length=255), nullable=True),
    sa.Column('responder_2', sa.String(length=255), nullable=True),
    sa.Column('responder_3', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_teams')
    # ### end Alembic commands ###
