"""adds team name to search teams

Revision ID: f2794bfbb152
Revises: 8f39f79ca308
Create Date: 2020-05-14 13:19:15.821036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2794bfbb152'
down_revision = '8f39f79ca308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_teams', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_teams', 'name')
    # ### end Alembic commands ###
