name: Deploy
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev

      - name: Run Test suite
        env:
          SECRET_KEY: somethingReallySecret
          FLASK_ENV: testing
        run: pipenv run make cov

#  deploy:
#    needs: test
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#
#      - name: Deploy to dokku
#        uses: idoberko2/dokku-deploy-github-action@v1
#        with:
#          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#          dokku-host: 'srv2.markrailton.com'
#          api-name: 'api.wwcd.pw'
#          git-push-flags: '--force'
#
#      - name: Create a Sentry.io release
#        uses: tclindner/sentry-releases-action@v1.0.0
#        env:
#          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
#          SENTRY_ORG: mark-railton
#          SENTRY_PROJECT: wwcd-api-production
#        with:
#          tagName: ${{ github.sha }}
#          environment: production